import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { GroceryItem } from "@/types";

// ✅ Register Hindi font (Google Noto Sans Devanagari)
Font.register({
  family: "NotoSansDevanagari",
  src: "/font/NotoSansDevanagari-Regular.ttf",
});

const tableColumns = ["S.No", "Item Name", "Quantity", "Unit", "Price"];

// 🎨 Styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: "#ffffff",
    fontSize: 11,
    padding: 30,
    fontFamily: "NotoSansDevanagari",
  },
  header: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 10,
    color: "#1e293b",
  },
  table: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ddd",
    marginTop: 10,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#ddd",
  },
  tableColHeader: {
    flex: 1,
    backgroundColor: "#4f46e5",
    color: "#fff",
    padding: 6,
    borderRightWidth: 1,
    borderColor: "#fff",
    textAlign: "center",
    fontWeight: "bold",
  },
  tableCol: {
    flex: 1,
    borderRightWidth: 1,
    borderColor: "#ddd",
    padding: 6,
    textAlign: "center",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 9,
    color: "#6b7280",
  },
});

type GroceryListPDFProps = {
  items: GroceryItem[];
  title: string;
};

const GroceryListPDF: React.FC<GroceryListPDFProps> = ({ items, title }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <Text style={styles.header}>{title}</Text>

      {/* Table */}
      <View style={styles.table}>
        {/* Header Row */}
        <View style={styles.tableRow}>
          {tableColumns.map((header, i) => (
            <Text key={i} style={styles.tableColHeader}>
              {header}
            </Text>
          ))}
        </View>

        {/* Body Rows */}
        {items.map((item, index) => (
          <View style={styles.tableRow} key={index}>
            <Text style={styles.tableCol}>{index + 1}</Text>
            <Text style={styles.tableCol}>{item.name}</Text>
            <Text style={styles.tableCol}>{item.quantity}</Text>
            <Text style={styles.tableCol}>{item.unit}</Text>

            {/* 👇 Price column left intentionally empty */}
            <Text style={styles.tableCol}></Text>
          </View>
        ))}
      </View>

      {/* Footer */}
      <Text
        style={styles.footer}
        render={({ pageNumber, totalPages }) =>
          `Generated by My Grocery App — Page ${pageNumber} of ${totalPages}`
        }
      />
    </Page>
  </Document>
);

export default GroceryListPDF;
